# Use PHP 8.3 FPM oficial
FROM php:8.3-fpm

# Diretório de trabalho dentro do container
WORKDIR /var/www/html

# Instala dependências do sistema
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libmagickwand-dev --no-install-recommends \
    imagemagick

# Instala extensões PHP necessárias
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instala extensão Imagick
RUN pecl install imagick && docker-php-ext-enable imagick

# Instala o Composer globalmente
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copia a aplicação para o container
COPY . /var/www/html

# Copia .env example
RUN cp .env.example .env

# Instala dependências do Laravel
RUN composer install --no-interaction --optimize-autoloader --no-dev

# Gera a key da aplicação
RUN php artisan key:generate

# Exponha a porta
EXPOSE 8000

# Comando para rodar o Laravel
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
